$(document).ready(function(){
    $("li.HaveSub").mouseenter(function(){
        $("div.SubSort").hide();
        $(this).children("div.SubSort").show();
    });
    $("li.HaveSub").mouseleave(function(){
        $(this).children("div.SubSort").hide();      
    });
});